/**
 * The version contract of this scaffold.
 *
 * `@rdmu/create-dsh-plugin` releases in lockstep with DeepSeek Harness: this
 * package's own version IS the dsh version a generated project depends on.
 * There is no `--dsh-version` flag — a person who wants a different dsh picks a
 * different scaffold release (`pnpm create @rdmu/dsh-plugin@0.1.0-rc.8 …`). One
 * version, one answer, nothing to keep in sync at generation time.
 *
 * Framework packages version independently of dsh (Cordis is on its own 4.x
 * line), so their ranges cannot be derived from this package's version and are
 * pinned here instead. Each range is the one the targeted dsh release declares
 * as its own peer or direct dependency.
 * @module @rdmu/create-dsh-plugin/versions
 */

import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

/**
 * Framework dependency ranges a generated project declares, keyed by package
 * name. These track the targeted dsh release's own declarations rather than
 * this package's version.
 *
 * Bump these together with the dsh version when re-releasing this scaffold:
 * read them off `npm view @deepseek-ai/dsh-tools@<version>` — `peerDependencies`
 * for `@deepseek-ai/cordis`, `dependencies` for `@deepseek-ai/schemastery`.
 */
export const FRAMEWORK_VERSIONS: Readonly<Record<string, string>> = {
  '@deepseek-ai/cordis': '^4.0.1',
  '@deepseek-ai/schemastery': '^3.18.1',
}

/**
 * Toolchain devDependency ranges a generated project declares. Independent of
 * the dsh version: these are the generated repository's own build and check
 * tools, chosen to match what deepseek-harness itself runs so a plugin
 * developed here meets the same standards.
 */
export const TOOLCHAIN_VERSIONS: Readonly<Record<string, string>> = {
  '@types/node': '^22.20.0',
  '@vitest/coverage-v8': '^4.1.8',
  'oxlint': '1.76.0',
  'oxlint-tsgolint': '7.0.2001',
  'tsdown': '^0.22.2',
  'tsx': '^4.22.4',
  'typescript': '^6.0.3',
  'vite-tsconfig-paths': '^6.1.1',
  'vitest': '^4.1.8',
}

/** The Node engines range a generated project declares (the dsh range). */
export const NODE_ENGINES = '^22.19.0 || >=24.0.0'

/** The pnpm version a generated project pins through `packageManager`. */
export const PACKAGE_MANAGER = 'pnpm@11.7.0'

/**
 * Read this package's own version — the dsh version generated projects target.
 *
 * Resolved from the package manifest at call time rather than inlined at build
 * time, so a published tarball and a source checkout report the same answer and
 * a version bump needs no rebuild.
 * @returns the semver string from this package's `package.json`.
 */
export function scaffoldVersion(): string {
  const manifestUrl = new URL('../package.json', import.meta.url)
  const raw = readFileSync(fileURLToPath(manifestUrl), 'utf8')
  const parsed = JSON.parse(raw) as { version?: unknown }
  /* v8 ignore next 4 -- this package's own manifest always declares a version, and versions.spec.ts asserts
     it matches the repository and template versions; the guard exists so a corrupted install fails here
     instead of writing a broken range into a generated project. */
  if (typeof parsed.version !== 'string' || parsed.version.length === 0) {
    throw new Error('create-dsh-plugin: own package.json declares no version')
  }
  return parsed.version
}

/**
 * Build the dependency range a generated project uses for every
 * `@deepseek-ai/dsh-*` package.
 *
 * Exact, not caret. A caret would defeat the whole point of releasing this
 * scaffold in lockstep with dsh: `^0.1.0-rc.7` also admits `0.1.0-rc.8` and
 * `0.1.0`, so a project generated by one scaffold release would silently install
 * a dsh the scaffold was never tested against. dsh packages are cut as one set
 * and are not independently compatible, so a range that mixes releases is a bug
 * waiting for a confusing type error.
 *
 * To move to a different dsh, generate with that scaffold release, or bump every
 * `@deepseek-ai/dsh-*` range in the project together.
 * @param version - the scaffold version from {@link scaffoldVersion}.
 * @returns the exact version string, e.g. `0.1.0-rc.7`.
 */
export function dshRange(version: string): string {
  return version
}
